import { build } from "esbuild";
import { mkdir, writeFile, readFile } from "node:fs/promises";
await mkdir("web/dist", { recursive: true });
await build({
  entryPoints: ["web/worker.js"],
  outfile: "web/dist/worker.js",
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["chrome100", "firefox100", "safari16"],
  legalComments: "external",
  sourcemap: false,
  minify: false,
});
await writeFile(
  "web/dist/BUILD.txt",
  "Generated by npm run build from pinned lockfile. Worker has no runtime network dependencies.\n",
);

const packages = [
  "@formatjs/icu-messageformat-parser",
  "@formatjs/icu-skeleton-parser",
  "@formatjs/fast-memoize",
  "intl-messageformat",
];
let notices =
  "THIRD-PARTY NOTICES — original dependency licenses, not a Locale Cases license grant.\n\n";
for (const name of packages)
  notices += `=== ${name} ===\n${await readFile(`node_modules/${name}/LICENSE.md`, "utf8")}\n\n`;
await writeFile("web/dist/THIRD_PARTY_LICENSES.txt", notices);
